[package]
name = "local"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.15.0"
rusqlite = { version = "0.28.0", features = ["modern-full", "time", "blob"] }
rusqlite_migration = "1.0.0"
thiserror = "1.0.37"
tokio = { version = "1.21.2", features = ["time", "sync"] }

[features]
default = ["bundled-sqlite"]
bundled-sqlite = ["rusqlite/bundled"]
